# Generated by Django 4.2.14 on 2024-07-11 10:56

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 11, 56, 36, 624165, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
